/* eslint-disable @next/next/no-css-tags */
/* eslint-disable react/jsx-key */

const headtags = [
  <title key="title">HighScoreWinsMoney</title>,
  <meta
    key="description"
    name="description"
    content="Generated by create next app"
  />,
  <link key="favicon" rel="icon" href="./favicon.ico" />,
  <link
    key="industry-font"
    href="./assets/fonts/Industry/stylesheet.css"
    rel="stylesheet"
  />,
  <link
    key="galactic-font"
    href="./assets/fonts/galactic-vanguardian-ncv/stylesheet.css"
    rel="stylesheet"
  />,
  <link
    key="chubby-font"
    href="./assets/fonts/ChubbyChoo/stylesheet.css"
    rel="stylesheet"
  />,
];

export default headtags;
