# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
# image: ubuntu:17.10

before_script:
  - apt-get update -qq
  - apt-get install -y -qq ssh
  - apt-get install -y -qq rsync
  - apt-get install -y -qq sshpass

  - mkdir ~/.ssh
  - echo "StrictHostKeyChecking no" >> ~/.ssh/config

  # - export SSHPASS=$TEST_SERVER_PASSWORD

stages:
  # - test
  - staging
# sast:
#   stage: test
# include:
#   - template: Security/SAST.gitlab-ci.yml

deploy-to-staging:
  variables:
    SSHPASS: $TEST_SERVER_PASSWORD
    REMOTE_USERNAME: testing2
    REMOTE_HOST: testing2.ttechr.com
    REMOTE_HOST_DIR: ./public_html/webroot/gitlab
    BUILD_DIR: ./nextjs-app/out
  stage: staging
  script:
    - pwd
    - ls -a $BUILD_DIR
    - sshpass -e rsync -avz --exclude='.git' $BUILD_DIR $REMOTE_USERNAME@$REMOTE_HOST:$REMOTE_HOST_DIR
