/* eslint-disable @next/next/no-css-tags */
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import HomePage from "../src/templates/pages/Home";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>HighScoreWinsMoney</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon.ico" />
        <link href="./assets/fonts/Industry/stylesheet.css" rel="stylesheet" />
        <link
          href="./assets/fonts/galactic-vanguardian-ncv/stylesheet.css"
          rel="stylesheet"
        />
        <link
          href="./assets/fonts/ChubbyChoo/stylesheet.css"
          rel="stylesheet"
        />
      </Head>

      <HomePage />

      <footer></footer>
    </div>
  );
};

export default Home;
