import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
// import logo from "../public/images/HS_reverse_portrait.png";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <span className={styles.logo}>
          This is the shit
          <img src={"images/HS_reverse_portrait.png"} />
          {/* <Image
            loader={({ src, width, quality }) => {
              return `https://example.com/${src}?w=${width}&q=${quality || 75}`;
            }}
            src={"./images/HS_reverse_portrait.png"}
            alt="HighScoreWinsMoney Logo"
            width={120 * 2}
            height={94 * 2}
          /> */}
        </span>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by <span className={styles.logo}></span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
